version: '3.9'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}

volumes:
  db_data:
