version: '3.9'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres_user}"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
  
  bot:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - bot_token=${bot_token}
      - postgres_dsn=postgresql+asyncpg://${postgres_user}:${postgres_password}@db:5432/${postgres_db}

volumes:
  db_data:
